### ISSUE TITLE
[3TR7] Pipeline reproduction (SPM - deriv)

### ISSUE THREAD

**Issue by alexpron** [Inria-Empenn/narps_open_pipelines#159]
### Softwares

+ fmriprep,
+ SPM12 (7219),
+ ipython and associated python packages (Python 3.6.7, matplotlib 3.0.3, pandas 0.24.1, and nilearn 0.5.0, nibabel 2.3.3,  numpy 1.16.2,
+ mricron for visual quality check

### Input data

derivatives (fMRIprep)

### Additional context

some subjects were excluded from the analysis based on predifined criteria

### List of tasks

Please tick the boxes below once the corresponding task is finished. :+1:
- [x] :ok_hand: A maintainer of the project approved the issue, by assigning a :checkered_flag:`status: ready for dev` label to it.
- [x] :deciduous_tree: Create a branch on your fork to start the reproduction.
- [x] :sunrise: Create a file `team_{team_id}.py` inside the [`narps_open/pipelines/`](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/narps_open/pipelines) directory. You can use a file inside [`narps_open/pipelines/templates`](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/narps_open/pipelines/templates) as a template if needed.
- [x] :inbox_tray: Create a [pull request](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/CONTRIBUTING.md#pull_requests) as soon as you completed the previous task.
- [ ] :brain: Write the code for the pipeline, using Nipype and the file architecture described in [docs/pipelines.md](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/docs/pipelines.md).
- [ ] :blue_book: Make sure your code is documented enough.
- [ ] :snake: Make sure your code is explicit and conforms with PEP8.
- [ ] :microscope: Create tests for your pipeline. You can use files in [`tests/pipelines/test_team_*`](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/tests/pipelines/) as examples.
- [ ] :microscope: Make sure your code passes all the tests you created (see [docs/testing.md](https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/docs/testing.md)).

**Comment by cmaumet** [comment]
@alexpron: I am adding you as assignee on this issue (just for the time of the hackathon) so that we can more easily see which pipelines are open for new contributions in https://github.com/orgs/Inria-Empenn/projects/1/views/1
