### ISSUE TITLE
Creation of a standard template to add a pipeline script

### ISSUE THREAD

**Issue by elodiegermani** [Inria-Empenn/narps_open_pipelines#2]
**Main purpose**:
Creation of a standard template of the reproduced pipelines with NiPype based on already reproduced pipelines to facilitate contributions. 

**Steps**:
- [x] Creation of a template file in the `src/lib` directory 
- [x] Add prefilled functions (similar to those in the reproduced pipelines scripts) that could be used by new contributors 
- [x] Add sufficient information (comments) for contributors to understand what they have to replace/add
- [x] Modify CONTRIBUTING.md with guidelines on how to use the template 
- [ ] Test of the template by someone who knows NiPype

**Comment by elodiegermani** [comment]
@bclenet I used the FSL template (`https://github.com/Inria-Empenn/narps_open_pipelines/blob/main/narps_open/pipelines/templates/template_fsl.py`) to reproduce a pipeline. There is a mistake line 36: `# [INFO] There was no run level analysis for the pipelines using FSL` -> it's the opposite. In FSL, there is a run-level analysis and then a subject-level one where you merge all runs :)

**Comment by bclenet** [comment]
Thanks @elodiegermani, it looks like my theoretical knowledge of FSL pipelines is wrong :sweat_smile:
Were you able to find other problems with that file or is it just that ? In other words : should I create a new issue for debugging the template ?
