### ISSUE TITLE
Debugging pre-implemented pipelines

### ISSUE THREAD

**Issue by elodiegermani** [Inria-Empenn/narps_open_pipelines#3]
**Main purpose**:
4 pipelines reproduction were started with different levels of implementation. 
For 3 of them, all analysis levels were pre-implemented but could not be validated due to differences between original and reproduced results (0I4U, 4TQ6, 1KB2). 
For the other one (43FJ), only the preprocessing was implemented but not functional due to an unidentified bug. 

**Steps**:
- [ ] 0I4U: Verification of the adequation between textual description and code, correction of mistakes (if necessary)
- [ ] 4TQ6: Verification of the adequation between textual description and code, correction of mistakes (if necessary)
- [ ] 1KB2: Verification of the adequation between textual description and code, correction of mistakes (if necessary)
- [ ] 43FJ: Bug correction in preprocessing function

**Comment by cmaumet** [comment]
Discussed with @elodiegermani - now closing this issue as the info has been moved to the corresponding team-specific issues.
