### ISSUE TITLE
Facilitate the link with public databases 

### ISSUE THREAD

**Issue by elodiegermani** [Inria-Empenn/narps_open_pipelines#4]
**Main purpose**: 
In this project, public databases are used to store the original data. Two types of data have to be downloaded: 
- Raw data from OpenNeuro (https://openneuro.org/datasets/ds001734/versions/1.0.4)
- Original results from NeuroVault (https://neurovault.org)
The aim of this issue is to find a way to automatically download original results and to facilitate the access to raw data (faster and automatic downloading) 

**Steps**:
- [ ] Write a script to automatically download raw data from OpenNeuro 
- [ ] Write a script to download original results (this can be done using pyneurovault or with custom functions, see [here](https://gitlab.inria.fr/egermani/analytic_variability_fmri/-/blob/master/results/lib/download_original_maps.py))

**Comment by Remi-Gau** [comment]
Will try to adapt this to get the neurovault data:

https://github.com/poldrack/narps/blob/1.0.1/ImageAnalyses/PrepareData.py
