### ISSUE TITLE
[ENH] Displaying the team dashboard in the README of this Github repo

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/narps_open_pipelines#44]
### Goal

Use github actions to display the team dashboard (as in narps_open.utils.status) in the README of this repo.

### Why this is useful

This would be useful to help contributors get a better understanding of which team reproductions are in progress, without having to download the full repo.

### Timeline

Soon?

### More specifically

Example of dashboard from #34 

<br>:red_circle: not started yet<br>:orange_circle: in progress<br>:green_circle: completed

| team_id | status | softwares used | fmriprep used ? | related issues |
| --- |:---:| --- | --- | --- |
| 0H5E | :red_circle: | SPM | No | |
| 0I4U | :orange_circle: | SPM | No | [3](https://github.com/Inria-Empenn/narps_open_pipelines/issues/3) |
| 0JO0 | :red_circle: | nistats | Yes | |
| 16IN | :red_circle: | matlab; SPM; Microsoft R Open; TExPosition; neuroim | Yes | |
| 1K0E | :red_circle: | nistats, FSL, HCP Workbench | No, but we did use fmriprep 1.1.8 | |
| 2P6S | :green_circle: | SPM | Yes | |
| ... | | | | |

**Comment by bclenet** [comment]
Hi @cmaumet, indeed it would be great !

For now, this dashboard is available in the project's wiki (see [here](https://github.com/Inria-Empenn/narps_open_pipelines/wiki/pipeline_status)). It is updated by GitHub Actions in either of these cases:

- when an issue is opened, edited, deleted, closed, or reopened ;
- when a commit related to pipeline files is done on the `main` branch.

Perhaps we could add a link to the wiki page in the README.md, possibly with an image to make the dashboard visible ?

**Comment by cmaumet** [comment]
@bclenet I knew I was missing something! Yes a link in the README + possible an image would be perfect! Thanks!

**Comment by cmaumet** [comment]
I think this issue can be closed. @bclenet is that right?
