### ISSUE TITLE
[ENH] Enhancing/bug? in the team dashboard

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/narps_open_pipelines#56]
### Goal

The team dashboard at https://github.com/Inria-Empenn/narps_open_pipelines/wiki/pipeline_status is a super entry point, very useful when trying to find which pipeline to contribute to. Here are a few suggestions to improve/update this view.

### Why this is useful

Suggestions : 
- It would be great to have the team dashboard sorted by the following columns : 1- "status", 2- "softwares used" and 3- "fmriprep used?"
- bug? 0H5E is currently marked as "in progress" but I can't find an issue or a PR with the code for this reproduction. Did I miss something?
- would be great to have an extra column named "PR" that links to the PR (even if work-in-progress) that would make it easier to discuss with the person contributing and possibly take over. (e.g. in my case I've started PR https://github.com/Inria-Empenn/narps_open_pipelines/pull/55 and would very much appreciate your help to continue the developement)
- I don't quite understand some of the issues that are linked in "related issues", e.g. for "0H5E" I see https://github.com/Inria-Empenn/narps_open_pipelines/issues/44 and I am not sure why?

**Comment by bclenet** [comment]
Hi @cmaumet, thanks for the input ! Here are a few answers.

A pipeline is considered as :orange_circle: as soon as one of the following statements is true : 
- a `narps_open/pipelines/team_<team-id>.py` file exists ;
- an *opened* issue (or pull request) refers to this pipeline (i.e.: either the title or the description of the issue contains the team id).

Hence, the second statement explains why 0H5E was marked as :orange_circle: : it was mentioned in issue #44, which I closed this morning. Now it is also mentioned in this issue #56, so once it is closed, the pipeline status will be back to :red_circle:.

For a pipeline to be :green_circle:, the `narps_open/pipelines/team_<team-id>.py` file must exist and no opened issues or pull request should remain.

Ok for the sorting strategy, and adding a PR column :+1: ! For now, PR are listed in the "related issues" column but it would be clearer with another column.
