### ISSUE TITLE
[ENH] Update the workflow so that reproduction PR are submitted as early as possible 

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/narps_open_pipelines#58]
### Goal

Currently in the template provided when reproducing a team's pipeline, submitting the corresponding PR is the last item on the list. Could we propose instead for the PR to be submitted right after the branch is created (i.e. "Create a file team_{team_id}.py inside the narps_open/pipelines/ directory. You can use a file inside narps_open/pipelines/templates file as a template if needed.")

### Why this is useful

This would make the work-in-progress code for different pipelines more easily accessible both to potential contributors but also to maintainers of this repo. This could be useful if the contributor would like to interact with mainteners / other contributors.

**Comment by bclenet** [comment]
Hi @cmaumet, you are right, and this would be more consistent with the documentation (contributing) as well. I'll fix that today !
